export const fr = {
  systemReady: "Système prêt",
  loading: "Chargement…",
  voyages: "Séances",
  minutes: "Minutes",
  streak: "Série",
  adaptiveSensors: "CAPTEURS ADAPTATIFS",
  sensorRec: "Recommandation système",
  lastSession: "Dernière séance",
  startSession: "Commencer",
  sessionsEmpty: "Séances épuisées · Accès illimité",
  sessions: "SÉANCES",
  viewAll: "Voir tout",
  collapse: "Réduire",
  bioBeats: "Beats Binauraux",
  ledFlash: "Torche LED",
  hertzWaves: "Ondes Hertziennes",
  haptic: "Haptique",
  hapticSub: "Patterns d'ondes adaptatifs",
  hertzSub: "Synchronisation neurale",
  langLabel: "FR",
  langFlag: "🇫🇷",
  langName: "Français",
  by: "par",
  rebootTitle: "RÉINITIALISATION B·R·S",
  rebootSub: "Réinitialisation complète du système bioadaptatif",
  rebootWarning: "Toutes tes données seront effacées — séances, journal, profil.",
  rebootConfirm: "RÉINITIALISER",
  rebootCancel: "Annuler",
  rebootProgress: "Réinitialisation en cours…",
  rebootDone: "Système réinitialisé",
  chooseLang: "Choisir la langue",
  tapSecret: "Fée Belette détectée ✦",
  deltaHz: "δ θ α Hz",
  freeSessions: "séances",
  // active session
  binauralActive: "Binaural actif",
  tapForControls: "Toucher pour les commandes",
  voyageDone: "Séance terminée",
  sessionNotFound: "Séance introuvable",
  sessionStarting: "Respire. La séance commence.",
  pausedWhisper: "On ne force rien.",
  torchAllow: "Torche — autoriser",
  torchDenied: "Torche — refusée",
  torchOff: "Torche — off",
  torchHz: "Torche",
  flashAllow: "Torche LED — toucher pour autoriser",
  flashNoPermission: "Autoriser la torche",
  flashActiveLabel: "Actif",
  flashDisabled: "Torche LED — Désactivée",
  intensityLabel: "Intensité",
  calmLevel: "Calme",
  moderateLevel: "Modéré",
  agitatedLevel: "Agité",
  darkLight: "Sombre",
  dimLight: "Tamisé",
  brightLight: "Lumineux",
  motionSensor: "MOUVEMENT",
  lightSensor: "LUMIÈRE",
  // profile
  profileTitle: "Profil",
  explorer: "Explorateur",
  relaxProfile: "Profil de relaxation",
  totalSessions: "Séances totales",
  totalTime: "Temps total",
  favSession: "Séance favorite",
  preferredMoment: "Moment préféré",
  morning: "Matin",
  afternoon: "Après-midi",
  evening: "Soir",
  night: "Nuit",
  sensoryPrefs: "Préférences sensorielles",
  vibrations: "Vibrations",
  hapticIntensityLabel: "Intensité haptique",
  lightLabel: "Lumière",
  chromaticIntensity: "Intensité chromatique",
  breathGuideLabel: "Guide respiratoire",
  breathAnimLabel: "Animation de respiration",
  sanctuaryModeLabel: "Mode Sanctuaire",
  noNotifLabel: "Aucune notification pendant les séances",
  lastVoyages: "Dernières séances",
  voyageOne: "séance accomplie",
  voyagePlural: "séances accomplies",
  minAbbr: "min",
  // journal
  voyageAccomplished: "Séance accomplie",
  howDoYouFeel: "Comment tu te sens ?",
  reflection: "Réflexion libre (optionnel)",
  notesPlaceholder: "Tes impressions…",
  returnToIsland: "Retour à l'espace",
  skip: "Passer",
  ratingHard: "Difficile",
  ratingOk: "Correct",
  ratingGood: "Bien",
  ratingVeryGood: "Très bien",
  ratingExcellent: "Excellent",
  // paywall
  paywallTitle: "Accès illimité",
  paywallSub: "Tous les rituels, sans restriction",
  paywallPrice: "4,99€ · Paiement unique",
  paywallCta: "Déverrouiller l'accès",
  paywallFree: "séances gratuites restantes",
  paywallRestore: "Restaurer l'achat",
  paywallLegal: "Paiement unique · Sans abonnement · Sans engagement",
  paywallUnlimited: "Séances illimitées",
  paywallAllWaves: "Toutes les ondes delta / thêta / alpha",
  paywallHistory: "Historique & graphiques complets",
  paywallSensors: "Synchronisation capteurs avancée",
  paywallFlash: "Torche LED stroboscopique",
  paywallFreeLabel: "3 séances offertes",
  // BreathingGuide phase labels
  inhale: "Inspirez",
  hold:   "Retenez",
  exhale: "Expirez",
  // BottomShelf
  profileBtnLabel: "PROFIL",
  adaptivePrefix:  "Adaptatif",
  sessionSingular: "séance",
  // Accordion science
  accordionTorchTitle:    "Torche LED · 3 modes cliniques",
  accordionTorchBody:     "La lumière pulsée à 40 Hz stimule la production d'ondes gamma — associées à la consolidation mémorielle et à la lucidité. Trois modes : Entrainement, Synchronisation respiratoire et Schumann (7.83 Hz).",
  accordionBinauralTitle: "Ondes binaurales · Alpha & Thêta",
  accordionBinauralBody:  "Deux fréquences légèrement distinctes, une par oreille. Le cerveau calcule la différence et entre en résonance avec elle — guidant l'activité neuronale vers l'état cible : calme, focus ou hypnagogie.",
  accordionSchumannTitle: "Résonance Schumann · 7.83 Hz",
  accordionSchumannBody:  "La cavité Terre-ionosphère résonne naturellement à 7.83 Hz — la même fréquence que l'état alpha-thêta humain. Cette session vous synchronise avec ce pouls planétaire fondamental.",
  // Adaptive session signals
  signalAgitation:   "Agitation élevée détectée",
  signalModerate:    "Niveau modéré détecté",
  signalCalm:        "État calme détecté",
  signalDark:        "Environnement sombre",
  signalBright:      "Environnement lumineux",
  signalNight:       "Heure : nuit",
  signalMorning:     "Heure : matin",
  signalMidMorning:  "Heure : matinée",
  signalAfternoon:   "Heure : après-midi",
  signalEvening:     "Heure : soirée",
  signalLateEvening: "Heure : fin de soirée",
  signalUsualSlot:   "Créneau habituel",
  signalFavorite:    "Favori",
  balancedParams:    "Paramètres équilibrés",
  // Adaptive labels (session names)
  adaptiveLabelRespiration: "Respiration Belette",
  adaptiveLabelReboot:      "Reboot Doux",
  adaptiveLabelNid:         "Nid de Calme",
  adaptiveLabelEtincelle:   "Étincelle Feuchienne",
  adaptiveLabelCristal:     "Cristal Intérieur",
  adaptiveLabelAurora:      "Aurora Belette",
  adaptiveLabelVague:       "Vague de Calme",
  adaptiveLabelRacine:      "Racine Feuchienne",
  // User level labels
  levelNeophyte:    "Néophyte Belette",
  levelInite:       "Initié·e Belette",
  levelPratiquant:  "Pratiquant·e Feuchien·ne",
  levelMaitre:      "Maître·sse Belette",
  // HomeScene — bubble labels
  bubbleRespire:   "Respire",
  bubbleNid:       "Nid",
  bubbleAurora:    "Aurora",
  bubbleCristal:   "Cristal",
  bubbleVague:     "Vague",
  bubbleReboot:    "Reboot",
  bubbleEtincelle: "Étincelle",
  // HomeScene — intention tags (petites pillules sous le label)
  tagRespire:   "↓ Stress",
  tagNid:       "↓ Anxiété",
  tagAurora:    "↑ Focus",
  tagCristal:   "✦ Méditation",
  tagVague:     "↓ Mental",
  tagReboot:    "↑ Énergie",
  tagEtincelle: "↑ Dopamine",
  // HomeScene — arc hook texts
  hookRespiration: "ALPHA 8 HZ · COHÉRENCE CARDIAQUE",
  hookNid:         "ALPHA 4 HZ · RESET CORTICAL",
  hookAurora:      "DELTA 2 HZ · RÉCUPÉRATION PROFONDE",
  hookCristal:     "SCHUMANN 7.83 HZ · ANCRAGE TERRESTRE",
  hookVague:       "THÊTA 5 HZ · LIBÉRATION MENTALE",
  hookReboot:      "THÊTA 3 HZ · ACTIVATION DOPAMINE",
  hookEtincelle:   "SMR 12 HZ · CLARTÉ COGNITIVE",
  hookRacine:      "DELTA 3 HZ · ANCRAGE ÉLECTROMAGNÉTIQUE",
  // FairyTutorialOverlay
  tutorialEyebrow:   "— COMMENT ÇA MARCHE —",
  tutorialTitle:     "La science\nderrière l'île.",
  tutorialSub:       "Fée Belette  ·  Système bioadaptif",
  tutorialCta:       "Je comprends · Allons-y",
  tutorial01Title:   "Binaural · Synchronise les ondes",
  tutorial01Body:    "Deux tons légèrement différents dans chaque oreille créent une fréquence perçue par le cerveau — delta pour le sommeil, alpha pour la clarté, theta pour la créativité.",
  tutorial02Title:   "Respiration guidée · Cohérence cardiaque",
  tutorial02Body:    "Chaque séance suit un rythme respiratoire précis. En 4–5 minutes, la variabilité cardiaque se stabilise et le cortisol baisse measurablement.",
  tutorial03Title:   "Lumière · Photostimulation douce",
  tutorial03Body:    "Certains rituels activent le flash LED en synchronie avec les ondes audio. La lumière stroboscopique à basse fréquence amplifie la réponse neuronale.",
  tutorial04Title:   "Capteurs · L'app s'adapte à toi",
  tutorial04Body:    "L'accéléromètre mesure ton niveau d'agitation. Le capteur de lumière détecte ton environnement. La séance choisie et l'intensité s'ajustent en temps réel.",
  // DurationPickerSheet
  howLong:      "Combien de temps ?",
  recommended:  "Recommandé",
  tagEclair:    "Éclair",
  tagStandard:  "Standard",
  tagImmersif:  "Immersif",
  tagSystem:    "Système",
  // Session subtitles
  subtitleRespiration: "Calme le corps, ralentit le mental",
  subtitleReboot:      "Revenir à zéro sans brutalité",
  subtitleNid:         "Relâcher la pression",
  subtitleEtincelle:   "Retrouver de l'élan sans se brusquer",
  subtitleCristal:     "Se recentrer",
  subtitleAurora:      "Clarté douce · Éveil progressif",
  subtitleVague:       "Laisser partir la pression accumulée",
  subtitleRacine:      "S'ancrer dans le présent",
  // Session science hooks
  scienceHookRespiration: "Torche synchronisée sur ta respiration · Cohérence alpha 8 Hz",
  scienceHookReboot:      "Torche LED à 4 Hz · Entraînement des ondes alpha · Reset cortical",
  scienceHookNid:         "Ondes delta 2 Hz · Récupération profonde · Immobilité sensorielle",
  scienceHookEtincelle:   "Rafales theta 3 Hz · Activation dopaminergique légère · TMS inspiré",
  scienceHookCristal:     "7.83 Hz · Fréquence naturelle terrestre · Ancrage électromagnétique",
  scienceHookAurora:      "SMR 12 Hz · Clarté cognitive sans tension · Beta bas apaisé",
  scienceHookVague:       "Thêta 5 Hz · Libération de la charge mentale · Océan intérieur",
  scienceHookRacine:      "Delta 3 Hz + 7.83 Hz · Ancrage électromagnétique profond",
  // Journal
  journalBrand:       "✦  FÉE BELETTE  ✦",
  journalSessionDone: "Séance terminée · ",
  journalTagline:     "On ne force rien. On revient doucement.",
  journalFeuchien:    "— FEUCHIEN APAISÉ —",
  journalReturnBtn:   "Revenir à l'île, doucement",
};
export type LangStrings = typeof fr;
