import { LangStrings } from "./fr";

export const es: LangStrings = {
  systemReady: "Sistema listo",
  loading: "Cargando…",
  voyages: "Sesiones",
  minutes: "Minutos",
  streak: "Racha",
  adaptiveSensors: "SENSORES ADAPTATIVOS",
  sensorRec: "Recomendación del sistema",
  lastSession: "Última sesión",
  startSession: "Comenzar",
  sessionsEmpty: "Sesiones agotadas · Acceso ilimitado",
  sessions: "SESIONES",
  viewAll: "Ver todo",
  collapse: "Cerrar",
  bioBeats: "Beats Binaurales",
  ledFlash: "Linterna LED",
  hertzWaves: "Ondas Hertz",
  haptic: "Háptica",
  hapticSub: "Patrones de ondas adaptativos",
  hertzSub: "Sincronización neural",
  langLabel: "ES",
  langFlag: "🇪🇸",
  langName: "Español",
  by: "por",
  rebootTitle: "REINICIO B·R·S",
  rebootSub: "Reinicio completo del sistema bioadaptativo",
  rebootWarning: "Todos tus datos serán borrados — sesiones, diario, perfil.",
  rebootConfirm: "REINICIAR",
  rebootCancel: "Cancelar",
  rebootProgress: "Reiniciando…",
  rebootDone: "Sistema reiniciado",
  chooseLang: "Elegir idioma",
  tapSecret: "Fée Belette detectada ✦",
  deltaHz: "δ θ α Hz",
  freeSessions: "sesiones",
  binauralActive: "Binaural activo",
  tapForControls: "Toca para controlar",
  sessionStarting: "Respira. La sesión comienza.",
  pausedWhisper: "Sin forzar.",
  torchAllow: "Linterna — autorizar",
  torchDenied: "Linterna — denegada",
  torchOff: "Linterna — apagada",
  torchHz: "Linterna",
  voyageDone: "Sesión completada",
  sessionNotFound: "Sesión no encontrada",
  flashAllow: "Linterna LED — toca para autorizar",
  flashNoPermission: "Permitir linterna",
  flashActiveLabel: "Activa",
  flashDisabled: "Linterna LED — Desactivada",
  intensityLabel: "Intensidad",
  calmLevel: "Calmado",
  moderateLevel: "Moderado",
  agitatedLevel: "Agitado",
  darkLight: "Oscuro",
  dimLight: "Tenue",
  brightLight: "Brillante",
  motionSensor: "MOVIMIENTO",
  lightSensor: "LUZ",
  profileTitle: "Perfil",
  explorer: "Explorador",
  relaxProfile: "Perfil de relajación",
  totalSessions: "Sesiones totales",
  totalTime: "Tiempo total",
  favSession: "Sesión favorita",
  preferredMoment: "Momento preferido",
  morning: "Mañana",
  afternoon: "Tarde",
  evening: "Noche",
  night: "Madrugada",
  sensoryPrefs: "Preferencias sensoriales",
  vibrations: "Vibraciones",
  hapticIntensityLabel: "Intensidad háptica",
  lightLabel: "Luz",
  chromaticIntensity: "Intensidad cromática",
  breathGuideLabel: "Guía respiratoria",
  breathAnimLabel: "Animación respiratoria",
  sanctuaryModeLabel: "Modo Santuario",
  noNotifLabel: "Sin notificaciones durante las sesiones",
  lastVoyages: "Sesiones recientes",
  voyageOne: "sesión completada",
  voyagePlural: "sesiones completadas",
  minAbbr: "min",
  voyageAccomplished: "Sesión completada",
  howDoYouFeel: "¿Cómo te sientes?",
  reflection: "Reflexión libre (opcional)",
  notesPlaceholder: "Tus impresiones…",
  returnToIsland: "Volver al espacio",
  skip: "Omitir",
  ratingHard: "Difícil",
  ratingOk: "Regular",
  ratingGood: "Bien",
  ratingVeryGood: "Muy bien",
  ratingExcellent: "Excelente",
  paywallTitle: "Acceso ilimitado",
  paywallSub: "Todos los rituales, sin restricciones",
  paywallPrice: "4,99€ · Pago único",
  paywallCta: "Desbloquear acceso",
  paywallFree: "sesiones gratuitas restantes",
  paywallRestore: "Restaurar compra",
  paywallLegal: "Pago único · Sin suscripción · Sin compromiso",
  paywallUnlimited: "Sesiones ilimitadas",
  paywallAllWaves: "Todas las ondas delta / theta / alfa",
  paywallHistory: "Historial y gráficos completos",
  paywallSensors: "Sincronización de sensores avanzada",
  paywallFlash: "Linterna LED estroboscópica",
  paywallFreeLabel: "3 sesiones incluidas",
  // BreathingGuide phase labels
  inhale: "Inhala",
  hold:   "Sostén",
  exhale: "Exhala",
  // BottomShelf
  profileBtnLabel: "PERFIL",
  adaptivePrefix:  "Adaptativo",
  sessionSingular: "sesión",
  // Accordion science
  accordionTorchTitle:    "Linterna LED · 3 modos clínicos",
  accordionTorchBody:     "La luz pulsada a 40 Hz estimula la producción de ondas gamma — asociadas a la consolidación de la memoria y la lucidez. Tres modos: Entrenamiento, Sincronización respiratoria y Schumann (7.83 Hz).",
  accordionBinauralTitle: "Beats binaurales · Alpha y Theta",
  accordionBinauralBody:  "Dos frecuencias ligeramente distintas, una por oído. El cerebro calcula la diferencia y entra en resonancia con ella — guiando la actividad neuronal hacia el estado objetivo: calma, enfoque o hipnagogia.",
  accordionSchumannTitle: "Resonancia Schumann · 7.83 Hz",
  accordionSchumannBody:  "La cavidad Tierra-ionosfera resuena naturalmente a 7.83 Hz — la misma frecuencia que el estado alfa-theta humano. Esta sesión te sincroniza con ese pulso planetario fundamental.",
  // Adaptive session signals
  signalAgitation:   "Alta agitación detectada",
  signalModerate:    "Nivel moderado detectado",
  signalCalm:        "Estado calmado detectado",
  signalDark:        "Entorno oscuro",
  signalBright:      "Entorno luminoso",
  signalNight:       "Hora: noche",
  signalMorning:     "Hora: mañana",
  signalMidMorning:  "Hora: mañana media",
  signalAfternoon:   "Hora: tarde",
  signalEvening:     "Hora: tarde-noche",
  signalLateEvening: "Hora: noche tardía",
  signalUsualSlot:   "Franja habitual",
  signalFavorite:    "Favorito",
  balancedParams:    "Parámetros equilibrados",
  // Adaptive labels (session names)
  adaptiveLabelRespiration: "Respiración Belette",
  adaptiveLabelReboot:      "Reboot Suave",
  adaptiveLabelNid:         "Nido de Calma",
  adaptiveLabelEtincelle:   "Chispa Feuchiana",
  adaptiveLabelCristal:     "Cristal Interior",
  adaptiveLabelAurora:      "Aurora Belette",
  adaptiveLabelVague:       "Ola de Calma",
  adaptiveLabelRacine:      "Raíz Feuchiana",
  // User level labels
  levelNeophyte:    "Neófito Belette",
  levelInite:       "Iniciado Belette",
  levelPratiquant:  "Practicante Feuchiano",
  levelMaitre:      "Maestro Belette",
  // HomeScene — bubble labels
  bubbleRespire:   "Respira",
  bubbleNid:       "Nido",
  bubbleAurora:    "Aurora",
  bubbleCristal:   "Cristal",
  bubbleVague:     "Ola",
  bubbleReboot:    "Reboot",
  bubbleEtincelle: "Chispa",
  // HomeScene — intention tags
  tagRespire:   "↓ Estrés",
  tagNid:       "↓ Ansiedad",
  tagAurora:    "↑ Foco",
  tagCristal:   "✦ Meditación",
  tagVague:     "↓ Mental",
  tagReboot:    "↑ Energía",
  tagEtincelle: "↑ Dopamina",
  // HomeScene — arc hook texts
  hookRespiration: "ALFA 8 HZ · COHERENCIA CARDÍACA",
  hookNid:         "ALFA 4 HZ · RESET CORTICAL",
  hookAurora:      "DELTA 2 HZ · RECUPERACIÓN PROFUNDA",
  hookCristal:     "SCHUMANN 7.83 HZ · ANCLAJE TERRESTRE",
  hookVague:       "THETA 5 HZ · LIBERACIÓN MENTAL",
  hookReboot:      "THETA 3 HZ · ACTIVACIÓN DOPAMINA",
  hookEtincelle:   "SMR 12 HZ · CLARIDAD COGNITIVA",
  hookRacine:      "DELTA 3 HZ · ANCLAJE ELECTROMAGNÉTICO",
  // FairyTutorialOverlay
  tutorialEyebrow:   "— CÓMO FUNCIONA —",
  tutorialTitle:     "La ciencia\ndetrás de la isla.",
  tutorialSub:       "Fée Belette  ·  Sistema bioadaptivo",
  tutorialCta:       "Entendido · Vamos",
  tutorial01Title:   "Binaural · Sincroniza las ondas",
  tutorial01Body:    "Dos tonos ligeramente distintos en cada oído crean una frecuencia percibida por el cerebro — delta para el sueño, alfa para la claridad, theta para la creatividad.",
  tutorial02Title:   "Respiración guiada · Coherencia cardíaca",
  tutorial02Body:    "Cada sesión sigue un ritmo respiratorio preciso. En 4–5 minutos, la variabilidad cardíaca se estabiliza y el cortisol baja de forma medible.",
  tutorial03Title:   "Luz · Fotoestimulación suave",
  tutorial03Body:    "Algunos rituales activan el flash LED sincronizado con las ondas de audio. La luz estroboscópica de baja frecuencia amplifica la respuesta neuronal.",
  tutorial04Title:   "Sensores · La app se adapta a ti",
  tutorial04Body:    "El acelerómetro mide tu nivel de agitación. El sensor de luz detecta tu entorno. La sesión elegida y la intensidad se ajustan en tiempo real.",
  // DurationPickerSheet
  howLong:      "¿Cuánto tiempo?",
  recommended:  "Recomendado",
  tagEclair:    "Rápido",
  tagStandard:  "Estándar",
  tagImmersif:  "Inmersivo",
  tagSystem:    "Sistema",
  // Session subtitles
  subtitleRespiration: "Calma el cuerpo, ralentiza la mente",
  subtitleReboot:      "Volver a cero sin brusquedad",
  subtitleNid:         "Soltar la presión",
  subtitleEtincelle:   "Recuperar el impulso sin prisas",
  subtitleCristal:     "Recentrarse",
  subtitleAurora:      "Claridad suave · Despertar progresivo",
  subtitleVague:       "Dejar ir la presión acumulada",
  subtitleRacine:      "Anclarse en el presente",
  // Session science hooks
  scienceHookRespiration: "Linterna sincronizada con tu respiración · Coherencia alfa 8 Hz",
  scienceHookReboot:      "Linterna LED a 4 Hz · Entrenamiento ondas alfa · Reset cortical",
  scienceHookNid:         "Ondas delta 2 Hz · Recuperación profunda · Inmovilidad sensorial",
  scienceHookEtincelle:   "Ráfagas theta 3 Hz · Activación dopaminérgica leve · Inspirado en TMS",
  scienceHookCristal:     "7.83 Hz · Frecuencia natural de la Tierra · Anclaje electromagnético",
  scienceHookAurora:      "SMR 12 Hz · Claridad cognitiva sin tensión · Beta bajo",
  scienceHookVague:       "Theta 5 Hz · Liberación de carga mental · Océano interior",
  scienceHookRacine:      "Delta 3 Hz + 7.83 Hz · Anclaje electromagnético profundo",
  // Journal
  journalBrand:       "✦  FÉE BELETTE  ✦",
  journalSessionDone: "Sesión completada · ",
  journalTagline:     "Sin forzar. Solo volver, suavemente.",
  journalFeuchien:    "— FEUCH EN PAZ —",
  journalReturnBtn:   "Volver a la isla, suavemente",
};
