import { LangStrings } from "./fr";

export const en: LangStrings = {
  systemReady: "System ready",
  loading: "Loading…",
  voyages: "Sessions",
  minutes: "Minutes",
  streak: "Streak",
  adaptiveSensors: "ADAPTIVE SENSORS",
  sensorRec: "System recommendation",
  lastSession: "Last session",
  startSession: "Start",
  sessionsEmpty: "Sessions used up · Go unlimited",
  sessions: "SESSIONS",
  viewAll: "View all",
  collapse: "Collapse",
  bioBeats: "Binaural Beats",
  ledFlash: "LED Torch",
  hertzWaves: "Hertz Waves",
  haptic: "Haptics",
  hapticSub: "Adaptive wave patterns",
  hertzSub: "Neural sync",
  langLabel: "EN",
  langFlag: "🇬🇧",
  langName: "English",
  by: "by",
  rebootTitle: "B·R·S RESET",
  rebootSub: "Full bioadaptive system reset",
  rebootWarning: "All your data will be erased — sessions, journal, profile.",
  rebootConfirm: "RESET SYSTEM",
  rebootCancel: "Cancel",
  rebootProgress: "Resetting…",
  rebootDone: "System reset",
  chooseLang: "Choose language",
  tapSecret: "Fée Belette detected ✦",
  deltaHz: "δ θ α Hz",
  freeSessions: "sessions",
  binauralActive: "Binaural active",
  tapForControls: "Touch for controls",
  sessionStarting: "Breathe. The session is starting.",
  pausedWhisper: "No forcing.",
  torchAllow: "Torch — allow",
  torchDenied: "Torch — denied",
  torchOff: "Torch — off",
  torchHz: "Torch",
  voyageDone: "Session complete",
  sessionNotFound: "Session not found",
  flashAllow: "LED Torch — tap to allow",
  flashNoPermission: "Allow torch",
  flashActiveLabel: "Active",
  flashDisabled: "LED Torch — Disabled",
  intensityLabel: "Intensity",
  calmLevel: "Calm",
  moderateLevel: "Moderate",
  agitatedLevel: "Agitated",
  darkLight: "Dark",
  dimLight: "Dim",
  brightLight: "Bright",
  motionSensor: "MOTION",
  lightSensor: "LIGHT",
  profileTitle: "Profile",
  explorer: "Explorer",
  relaxProfile: "Relaxation profile",
  totalSessions: "Total sessions",
  totalTime: "Total time",
  favSession: "Favourite session",
  preferredMoment: "Preferred time",
  morning: "Morning",
  afternoon: "Afternoon",
  evening: "Evening",
  night: "Night",
  sensoryPrefs: "Sensory preferences",
  vibrations: "Vibrations",
  hapticIntensityLabel: "Haptic intensity",
  lightLabel: "Light",
  chromaticIntensity: "Chromatic intensity",
  breathGuideLabel: "Breathing guide",
  breathAnimLabel: "Breathing animation",
  sanctuaryModeLabel: "Sanctuary Mode",
  noNotifLabel: "No notifications during sessions",
  lastVoyages: "Recent sessions",
  voyageOne: "session completed",
  voyagePlural: "sessions completed",
  minAbbr: "min",
  voyageAccomplished: "Session complete",
  howDoYouFeel: "How are you feeling?",
  reflection: "Free reflection (optional)",
  notesPlaceholder: "Your impressions…",
  returnToIsland: "Back to space",
  skip: "Skip",
  ratingHard: "Difficult",
  ratingOk: "Fair",
  ratingGood: "Good",
  ratingVeryGood: "Very good",
  ratingExcellent: "Excellent",
  paywallTitle: "Unlimited access",
  paywallSub: "All rituals, no restrictions",
  paywallPrice: "€4.99 · One-time",
  paywallCta: "Unlock access",
  paywallFree: "free sessions remaining",
  paywallRestore: "Restore purchase",
  paywallLegal: "One-time payment · No subscription · No commitment",
  paywallUnlimited: "Unlimited sessions",
  paywallAllWaves: "All delta / theta / alpha waves",
  paywallHistory: "Full history & charts",
  paywallSensors: "Advanced sensor sync",
  paywallFlash: "Stroboscopic LED torch",
  paywallFreeLabel: "3 sessions included",
  // BreathingGuide phase labels
  inhale: "Inhale",
  hold:   "Hold",
  exhale: "Exhale",
  // BottomShelf
  profileBtnLabel: "PROFILE",
  adaptivePrefix:  "Adaptive",
  sessionSingular: "session",
  // Accordion science
  accordionTorchTitle:    "LED Torch · 3 clinical modes",
  accordionTorchBody:     "Pulsed light at 40 Hz stimulates gamma wave production — linked to memory consolidation and clarity. Three modes: Entrainment, Breath Sync and Schumann (7.83 Hz).",
  accordionBinauralTitle: "Binaural beats · Alpha & Theta",
  accordionBinauralBody:  "Two slightly different frequencies, one per ear. The brain computes the difference and resonates with it — guiding neural activity toward the target state: calm, focus or hypnagogia.",
  accordionSchumannTitle: "Schumann Resonance · 7.83 Hz",
  accordionSchumannBody:  "The Earth-ionosphere cavity resonates naturally at 7.83 Hz — the same frequency as the human alpha-theta state. This session synchronises you with that fundamental planetary pulse.",
  // Adaptive session signals
  signalAgitation:   "High agitation detected",
  signalModerate:    "Moderate level detected",
  signalCalm:        "Calm state detected",
  signalDark:        "Dark environment",
  signalBright:      "Bright environment",
  signalNight:       "Time: night",
  signalMorning:     "Time: morning",
  signalMidMorning:  "Time: mid-morning",
  signalAfternoon:   "Time: afternoon",
  signalEvening:     "Time: evening",
  signalLateEvening: "Time: late evening",
  signalUsualSlot:   "Usual time slot",
  signalFavorite:    "Favourite",
  balancedParams:    "Balanced settings",
  // Adaptive labels (session names)
  adaptiveLabelRespiration: "Belette Breathing",
  adaptiveLabelReboot:      "Gentle Reboot",
  adaptiveLabelNid:         "Calm Nest",
  adaptiveLabelEtincelle:   "Feuchian Spark",
  adaptiveLabelCristal:     "Inner Crystal",
  adaptiveLabelAurora:      "Belette Aurora",
  adaptiveLabelVague:       "Calm Wave",
  adaptiveLabelRacine:      "Feuchian Root",
  // User level labels
  levelNeophyte:    "Belette Neophyte",
  levelInite:       "Belette Initiate",
  levelPratiquant:  "Feuchian Practitioner",
  levelMaitre:      "Belette Master",
  // HomeScene — bubble labels
  bubbleRespire:   "Breathe",
  bubbleNid:       "Nest",
  bubbleAurora:    "Aurora",
  bubbleCristal:   "Crystal",
  bubbleVague:     "Wave",
  bubbleReboot:    "Reboot",
  bubbleEtincelle: "Spark",
  // HomeScene — intention tags
  tagRespire:   "↓ Stress",
  tagNid:       "↓ Anxiety",
  tagAurora:    "↑ Focus",
  tagCristal:   "✦ Meditation",
  tagVague:     "↓ Mental",
  tagReboot:    "↑ Energy",
  tagEtincelle: "↑ Dopamine",
  // HomeScene — arc hook texts
  hookRespiration: "ALPHA 8 HZ · CARDIAC COHERENCE",
  hookNid:         "ALPHA 4 HZ · CORTICAL RESET",
  hookAurora:      "DELTA 2 HZ · DEEP RECOVERY",
  hookCristal:     "SCHUMANN 7.83 HZ · EARTH GROUNDING",
  hookVague:       "THETA 5 HZ · MENTAL RELEASE",
  hookReboot:      "THETA 3 HZ · DOPAMINE ACTIVATION",
  hookEtincelle:   "SMR 12 HZ · COGNITIVE CLARITY",
  hookRacine:      "DELTA 3 HZ · ELECTROMAGNETIC GROUNDING",
  // FairyTutorialOverlay
  tutorialEyebrow:   "— HOW IT WORKS —",
  tutorialTitle:     "The science\nbehind the island.",
  tutorialSub:       "Fée Belette  ·  Bioadaptive System",
  tutorialCta:       "Got it · Let's go",
  tutorial01Title:   "Binaural · Synchronises brain waves",
  tutorial01Body:    "Two slightly different tones in each ear create a frequency perceived by the brain — delta for sleep, alpha for clarity, theta for creativity.",
  tutorial02Title:   "Guided breathing · Cardiac coherence",
  tutorial02Body:    "Each session follows a precise breathing rhythm. In 4–5 minutes, heart rate variability stabilises and cortisol drops measurably.",
  tutorial03Title:   "Light · Gentle photo-stimulation",
  tutorial03Body:    "Some rituals activate the LED flash in sync with audio waves. Low-frequency strobe light amplifies the neural response.",
  tutorial04Title:   "Sensors · The app adapts to you",
  tutorial04Body:    "The accelerometer measures your agitation level. The light sensor detects your environment. The session and intensity adjust in real time.",
  // DurationPickerSheet
  howLong:      "How long?",
  recommended:  "Recommended",
  tagEclair:    "Flash",
  tagStandard:  "Standard",
  tagImmersif:  "Immersive",
  tagSystem:    "System",
  // Session subtitles
  subtitleRespiration: "Calms the body, slows the mind",
  subtitleReboot:      "Return to zero, gently",
  subtitleNid:         "Release the pressure",
  subtitleEtincelle:   "Rediscover momentum without rushing",
  subtitleCristal:     "Re-centre yourself",
  subtitleAurora:      "Soft clarity · Gradual awakening",
  subtitleVague:       "Let accumulated pressure go",
  subtitleRacine:      "Ground yourself in the present",
  // Session science hooks
  scienceHookRespiration: "Torch synced to your breathing · Alpha coherence 8 Hz",
  scienceHookReboot:      "LED torch at 4 Hz · Alpha wave entrainment · Cortical reset",
  scienceHookNid:         "Delta waves 2 Hz · Deep recovery · Sensory stillness",
  scienceHookEtincelle:   "Theta bursts 3 Hz · Light dopaminergic activation · TMS-inspired",
  scienceHookCristal:     "7.83 Hz · Earth's natural frequency · Electromagnetic grounding",
  scienceHookAurora:      "SMR 12 Hz · Cognitive clarity without tension · Low beta",
  scienceHookVague:       "Theta 5 Hz · Mental load release · Inner ocean",
  scienceHookRacine:      "Delta 3 Hz + 7.83 Hz · Deep electromagnetic grounding",
  // Journal
  journalBrand:       "✦  FÉE BELETTE  ✦",
  journalSessionDone: "Session complete · ",
  journalTagline:     "No forcing. Just coming back, gently.",
  journalFeuchien:    "— FEUCH AT PEACE —",
  journalReturnBtn:   "Return to the island, gently",
};
