/**
 * SESSION_WHISPERS_I18N
 * Poetic whispers cycling every 14 s during a session — translated in fr/en/es.
 */
export const SESSION_WHISPERS_I18N: Record<string, Record<string, string[]>> = {
  fr: {
    respiration: [
      "Respire. Je suis là.",
      "Inspire. La lumière suit ton souffle.",
      "Expire. Tu n'as rien à prouver.",
      "On ne force rien. On revient doucement.",
      "Le Feuch s'agite ? On lui met une couverture.",
      "Chaque expiration efface un peu plus le bruit.",
    ],
    reboot: [
      "Reboot en cours. Aucun drame détecté.",
      "La lumière pulse. Ton cerveau s'aligne.",
      "Inspire. Le système se repose.",
      "Tu n'as rien à prouver. Rien du tout.",
      "4 Hz. Alpha. Remise à zéro en cours.",
      "Le reset prend du temps. C'est normal.",
    ],
    nid: [
      "Respire. Je suis là.",
      "Expire. Relâche la pression.",
      "Tu es en sécurité. Le nid t'accueille.",
      "Rien à faire. Juste être là.",
      "La fatigue fond doucement. C'est bien.",
      "Deux hertz. Le corps récupère.",
    ],
    etincelle: [
      "Une petite étincelle suffit.",
      "Inspire. Sens l'élan qui revient doucement.",
      "Pas besoin de tout. Juste un peu de lumière.",
      "Expire. Garde l'étincelle.",
      "Doucement. L'île te redonne de l'élan.",
      "Rafale theta. L'énergie remonte.",
    ],
    cristal: [
      "Le cristal intérieur se stabilise.",
      "7.83 Hz. La fréquence de la Terre.",
      "Expire. Laisse le bruit partir.",
      "Tu es plus ancré que tu ne le crois.",
      "Recentre. Doucement. Voilà.",
      "La Terre pulse avec toi.",
    ],
    aurora: [
      "L'aube intérieure se lève.",
      "SMR 12 Hz. La clarté arrive doucement.",
      "Inspire. Sens la luminosité croître.",
      "Ton esprit s'éveille. Pas de brusquerie.",
      "Aurora. Clarté sans tension.",
      "12 Hz. Le seuil entre calme et éveil.",
    ],
    vague: [
      "La vague arrive. Elle emporte le trop-plein.",
      "Thêta 5 Hz. L'océan intérieur.",
      "Expire. Laisse la vague partir.",
      "Rien à retenir. Tout peut partir.",
      "La pression se dissout dans l'eau.",
      "Vague après vague. Le calme revient.",
    ],
    racine: [
      "Tes pieds dans la Terre.",
      "Delta 3 Hz. Ton corps descend dans le sol.",
      "Schumann pulse. La Terre te tient.",
      "Ancré. Présent. Ici.",
      "Le Feuch peut poser son bagage.",
      "7.83 Hz. Tu es synchronisé avec la planète.",
    ],
  },

  en: {
    respiration: [
      "Breathe. I'm here.",
      "Inhale. The light follows your breath.",
      "Exhale. You have nothing to prove.",
      "No forcing. Just coming back, gently.",
      "Mind racing? Let's give it a blanket.",
      "Each exhale dissolves a little more noise.",
    ],
    reboot: [
      "Reboot in progress. No drama detected.",
      "The light pulses. Your brain aligns.",
      "Inhale. The system is resting.",
      "Nothing to prove. Nothing at all.",
      "4 Hz. Alpha. Reset underway.",
      "The reset takes time. That's normal.",
    ],
    nid: [
      "Breathe. I'm here.",
      "Exhale. Release the pressure.",
      "You are safe. The nest welcomes you.",
      "Nothing to do. Just be here.",
      "Fatigue melting slowly. That's good.",
      "Two hertz. The body recovers.",
    ],
    etincelle: [
      "A little spark is enough.",
      "Inhale. Feel the momentum returning gently.",
      "You don't need everything. Just a little light.",
      "Exhale. Keep the spark.",
      "Gently. The island gives you momentum back.",
      "Theta burst. Energy rising.",
    ],
    cristal: [
      "The inner crystal stabilises.",
      "7.83 Hz. Earth's own frequency.",
      "Exhale. Let the noise go.",
      "You are more grounded than you think.",
      "Re-centre. Gently. There.",
      "The Earth pulses with you.",
    ],
    aurora: [
      "The inner dawn rises.",
      "SMR 12 Hz. Clarity arriving gently.",
      "Inhale. Feel the brightness grow.",
      "Your mind awakens. No rushing.",
      "Aurora. Clarity without tension.",
      "12 Hz. The threshold between calm and waking.",
    ],
    vague: [
      "The wave arrives. It carries away the excess.",
      "Theta 5 Hz. Inner ocean.",
      "Exhale. Let the wave go.",
      "Nothing to hold. Everything can leave.",
      "Pressure dissolving in the water.",
      "Wave after wave. Calm returns.",
    ],
    racine: [
      "Your feet in the Earth.",
      "Delta 3 Hz. Your body sinks into the ground.",
      "Schumann pulses. The Earth holds you.",
      "Grounded. Present. Here.",
      "The mind can set down its load.",
      "7.83 Hz. Synchronised with the planet.",
    ],
  },

  es: {
    respiration: [
      "Respira. Estoy aquí.",
      "Inhala. La luz sigue tu aliento.",
      "Exhala. No tienes nada que demostrar.",
      "Sin forzar. Solo volviendo, suavemente.",
      "¿Mente acelerada? Vamos a arroparla.",
      "Cada exhalación disuelve un poco más el ruido.",
    ],
    reboot: [
      "Reinicio en curso. Ningún drama detectado.",
      "La luz pulsa. Tu cerebro se alinea.",
      "Inhala. El sistema descansa.",
      "Nada que demostrar. Nada en absoluto.",
      "4 Hz. Alfa. Reset en marcha.",
      "El reset lleva tiempo. Es normal.",
    ],
    nid: [
      "Respira. Estoy aquí.",
      "Exhala. Suelta la presión.",
      "Estás seguro. El nido te acoge.",
      "Nada que hacer. Solo estar aquí.",
      "El cansancio se disuelve suavemente. Bien.",
      "Dos hercios. El cuerpo se recupera.",
    ],
    etincelle: [
      "Una pequeña chispa basta.",
      "Inhala. Siente el impulso volviendo suavemente.",
      "No necesitas todo. Solo un poco de luz.",
      "Exhala. Guarda la chispa.",
      "Suavemente. La isla te devuelve el impulso.",
      "Ráfaga theta. La energía sube.",
    ],
    cristal: [
      "El cristal interior se estabiliza.",
      "7.83 Hz. La frecuencia de la Tierra.",
      "Exhala. Deja ir el ruido.",
      "Estás más anclado de lo que crees.",
      "Recentra. Suavemente. Ahí.",
      "La Tierra pulsa contigo.",
    ],
    aurora: [
      "El amanecer interior se eleva.",
      "SMR 12 Hz. La claridad llega suavemente.",
      "Inhala. Siente crecer la luminosidad.",
      "Tu mente despierta. Sin brusquedad.",
      "Aurora. Claridad sin tensión.",
      "12 Hz. El umbral entre calma y despertar.",
    ],
    vague: [
      "La ola llega. Se lleva lo que sobra.",
      "Theta 5 Hz. Océano interior.",
      "Exhala. Deja ir la ola.",
      "Nada que retener. Todo puede irse.",
      "La presión se disuelve en el agua.",
      "Ola tras ola. La calma vuelve.",
    ],
    racine: [
      "Tus pies en la Tierra.",
      "Delta 3 Hz. Tu cuerpo se hunde en el suelo.",
      "Schumann pulsa. La Tierra te sostiene.",
      "Anclado. Presente. Aquí.",
      "La mente puede soltar su carga.",
      "7.83 Hz. Sincronizado con el planeta.",
    ],
  },
};

export function getSessionWhispers(id: string, lang: string): string[] {
  const langKey = lang === "EN" ? "en" : lang === "ES" ? "es" : "fr";
  return SESSION_WHISPERS_I18N[langKey]?.[id] ?? SESSION_WHISPERS_I18N["fr"]?.[id] ?? [];
}
